### ISSUE TITLE
Graylog not running due to MongoDB {cannot resolve host Issue and {Name or service not known issue}}

### ISSUE THREAD

**Issue by akramwaseem** [KongZ/charts#43]
Hi, 
I am running the Helm chart version https://artifacthub.io/packages/helm/kong-z/graylog/1.7.4

When MongoDB pod starts it gives me error
```bash

2021-04-30T21:15:39.280496009Z mongodb 21:15:39.27 INFO  ==> ** Starting MongoDB setup **
2021-04-30T21:15:39.295730088Z mongodb 21:15:39.29 INFO  ==> Validating settings in MONGODB_* env vars...
2021-04-30T21:15:39.297866239Z mongodb 21:15:39.29 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
2021-04-30T21:15:39.316485058Z mongodb 21:15:39.31 INFO  ==> Initializing MongoDB...
2021-04-30T21:15:39.338779337Z mongodb 21:15:39.33 INFO  ==> Deploying MongoDB from scratch...
2021-04-30T21:15:40.282615079Z mongodb 21:15:40.28 INFO  ==> Creating users...
2021-04-30T21:15:40.284855437Z mongodb 21:15:40.28 INFO  ==> Users created
2021-04-30T21:15:40.310032821Z mongodb 21:15:40.30 INFO  ==> Configuring MongoDB replica set...
2021-04-30T21:15:40.317475548Z mongodb 21:15:40.31 INFO  ==> Stopping MongoDB...
2021-04-30T21:15:42.834718518Z mongodb 21:15:42.83 INFO  ==> Trying to connect to MongoDB server graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local...
2021-04-30T21:15:42.913794118Z cannot resolve host "graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local": lookup graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local: no such host
2021-04-30T21:15:47.932019406Z cannot resolve host "graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local": lookup graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local: no such host
2021-04-30T21:15:52.951088854Z cannot resolve host "graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local": lookup graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local: no such host
2021-04-30T21:15:58.029791824Z cannot resolve host "graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local": lookup graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local: no such host
2021-04-30T21:16:03.110453834Z cannot resolve host "graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local": lookup graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local: no such host

```

Anyone have an idea on what I can do to solve this issue ?

In the meantime on the Graylog side

```bash

2021-04-30T21:16:48.425748931Z 2021-04-30 21:16:48,425 INFO    [LogManager] - Logs loading complete. - {}
2021-04-30T21:16:48.428776245Z 2021-04-30 21:16:48,428 INFO    [KafkaJournal] - Initialized Kafka based journal at /usr/share/graylog/data/journal - {}
2021-04-30T21:16:48.454634976Z 2021-04-30 21:16:48,454 INFO    [cluster] - Cluster created with settings {hosts=[graylog-mongodb-headless.svfb.svc.cluster.local:27017], mode=MULTIPLE, requiredClusterType=REPLICA_SET, serverSelectionTimeout='30000 ms', maxWaitQueueSize=5000, requiredReplicaSetName='rs0'} - {}
2021-04-30T21:16:48.454684180Z 2021-04-30 21:16:48,454 INFO    [cluster] - Adding discovered server graylog-mongodb-headless.svfb.svc.cluster.local:27017 to client view of cluster - {}
2021-04-30T21:16:48.540199336Z 2021-04-30 21:16:48,539 INFO    [cluster] - No server chosen by com.mongodb.client.internal.MongoClientDelegate$1@6dded900 from cluster description ClusterDescription{type=REPLICA_SET, connectionMode=MULTIPLE, serverDescriptions=[ServerDescription{address=graylog-mongodb-headless.svfb.svc.cluster.local:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out - {}
2021-04-30T21:16:48.546681095Z 2021-04-30 21:16:48,539 INFO    [cluster] - Exception in monitor thread while connecting to server graylog-mongodb-headless.svfb.svc.cluster.local:27017 - {}
2021-04-30T21:16:48.546699096Z com.mongodb.MongoSocketException: graylog-mongodb-headless.svfb.svc.cluster.local: Name or service not known
2021-04-30T21:16:48.546704297Z 	at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:211) ~[graylog.jar:?]
2021-04-30T21:16:48.546708997Z 	at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:75) ~[graylog.jar:?]
2021-04-30T21:16:48.546713597Z 	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:65) ~[graylog.jar:?]
2021-04-30T21:16:48.546717898Z 	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:128) ~[graylog.jar:?]
2021-04-30T21:16:48.546722298Z 	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) [graylog.jar:?]
2021-04-30T21:16:48.546727598Z 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
2021-04-30T21:16:48.546732199Z Caused by: java.net.UnknownHostException: graylog-mongodb-headless.svfb.svc.cluster.local: Name or service not known
2021-04-30T21:16:48.546736499Z 	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0_282]
2021-04-30T21:16:48.546740599Z 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929) ~[?:1.8.0_282]
2021-04-30T21:16:48.546744800Z 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324) ~[?:1.8.0_282]
2021-04-30T21:16:48.546749000Z 	at java.net.InetAddress.getAllByName0(InetAddress.java:1277) ~[?:1.8.0_282]
2021-04-30T21:16:48.546753200Z 	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:1.8.0_282]
2021-04-30T21:16:48.546757400Z 	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:1.8.0_282]
2021-04-30T21:16:48.546761401Z 	at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:203) ~[graylog.jar:?]
2021-04-30T21:16:48.546765701Z 	... 5 more

```

Helm Chart with little Modifications

```yaml

# Default values for Graylog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rbac:
  # Specifies whether RBAC resources should be created
  ##
  create: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  ##
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  ##
  name:

graylog:

  persistence:
    ## If true, Graylog will create/use a Persistent Volume Claim
    ## If false, use emptyDir
    ##
    enabled: true
    ## Graylog data Persistent Volume access modes
    ## Must match those of existing PV or dynamic provisioner
    ## Ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    accessMode: ReadWriteOnce
    ## Graylog data Persistent Volume size
    ##
    size: "20Gi"
    ## Graylog data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "ssd"

  ## Additional plugins you need to install on Graylog.
  ##
  plugins: []
    # - name: graylog-plugin-slack-2.7.1.jar
    #   url: https://github.com/omise/graylog-plugin-slack/releases/download/2.7.1/graylog-plugin-slack-2.7.1.jar
    # - name: graylog-plugin-function-check-diff-1.0.0.jar
    #   url: https://github.com/omise/graylog-plugin-function-check-diff/releases/download/1.0.0/graylog-plugin-function-check-diff-1.0.0.jar
    # - name: graylog-plugin-custom-alert-condition-1.0.0.jar
    #   url: https://github.com/omise/graylog-plugin-custom-alert-condition/releases/download/v1.0.0/graylog-plugin-custom-alert-condition-1.0.0.jar
    # - name: graylog-plugin-auth-sso-3.0.0.jar
    #   url: https://github.com/Graylog2/graylog-plugin-auth-sso/releases/download/3.0.0/graylog-plugin-auth-sso-3.0.0.jar

  ## A service for Graylog web interface
  ##
  service:
    type: ClusterIP
    port: 9000

    master:
      ## Graylog master service Ingress annotations
      ##
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      ## Graylog master service port.
      ##

  ## Additional input ports for receiving logs from servers
  ## Note: Name must be in IANA_SVC_NAME (at most 15 characters, matching regex [a-z0-9]([a-z0-9-]*[a-z0-9])* and it must contains at least one letter [a-z], hyphens cannot be adjacent to other hyphens)
  ## Note: Array must be sorted by port order
  ##
  input:
    tcp:
      service:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      ports:
        - name: raw-tcp-6655
          port: 6655
        - name: gelf-tcp-12201
          port: 12201
        - name: filebeat-5044
          port: 5044

  metrics:
    ## If true, prometheus annotations will be attached
    ##
    enabled: true

  ingress:
    ## If true, Graylog server Ingress will be created
    ##
    enabled: true
    ## Graylog server Ingress annotations
    ##
    annotations:
      kubernetes.io/ingress.class: nginx
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    ## Graylog server Ingress hostnames with optional path
    ## Must be provided if Ingress is enabled
    ## Note: Graylog does not support two URL. You can specify only single URL
    ##
    hosts:
       - graylog-test.${config_DOMAIN}

    ## Graylog server Ingress TLS configuration
    ## Secrets must be manually created in the namespace
    ##
    tls:
    #   - secretName: graylog-server-tls
       - hosts:
           - graylog.${config_DOMAIN}
  provisioner:
      enabled: true
      script: |
        json='{
          "title":"Raw TCP",
          "type":"org.graylog2.inputs.raw.tcp.RawTCPInput",
          "configuration":{
            "bind_address":"0.0.0.0",
            "port":6655
            },
          "global":true
        }'
        printf "Launching Raw TCP..."
        # 5 min for the first request to wait for graylog-web init
        curl --output /dev/null --silent \\
          -u "admin:$GRAYLOG_PASSWORD_SECRET" \\
          -H "Content-Type: application/json" -H "x-requested-by: localhost" \\
          -d "$json" http://graylog-web:9000/api/system/inputs \\
          --connect-timeout 10 \\
          --retry 20 \\
          --max-time 20 \\
          --retry-max-time 300 \\
          --retry-connrefused

        if [[ $? -ne 0 ]]; then
          echo " Creation failed."
        else
          echo
        fi

        json='{
          "title":"GELF TCP",
          "type":"org.graylog2.inputs.gelf.tcp.GELFTCPInput",
          "configuration":{
            "bind_address":"0.0.0.0",
            "port":12201
          },
          "global":true
        }'
        printf "Launching GELF TCP..."
        curl --output /dev/null --silent \\
          -u "admin:$GRAYLOG_PASSWORD_SECRET" \\
          -H "Content-Type: application/json" -H "x-requested-by: localhost" \\
          -d "$json" http://graylog-web:9000/api/system/inputs \\
          --connect-timeout 10 \\
          --retry 20 \\
          --max-time 20 \\
          --retry-max-time 120 \\
          --retry-connrefused

        if [[ $? -ne 0 ]]; then
          echo " Creation failed."
        else
          echo
        fi

        json='{
          "title":"Raw UDP",
          "type":"org.graylog2.inputs.raw.udp.RawUDPInput",
          "configuration":{
            "bind_address":"0.0.0.0",
            "port":6556
          },
          "global":true
        }'
        printf "Launching Raw UDP..."
        curl --output /dev/null --silent \\
          -u "admin:$GRAYLOG_PASSWORD_SECRET" \\
          -H "Content-Type: application/json" -H "x-requested-by: localhost" \\
          -d "$json" http://graylog-web:9000/api/system/inputs \\
          --connect-timeout 10 \\
          --retry 20 \\
          --max-time 20 \\
          --retry-max-time 120 \\
          --retry-connrefused

        if [[ $? -ne 0 ]]; then
          echo " Creation failed."
        else
          echo
        fi

        json='{
          "title":"GELF UDP",
          "type":"org.graylog2.inputs.gelf.udp.GELFUDPInput",
          "configuration":{
            "bind_address":"0.0.0.0",
            "port":6601
          },
          "global":true
        }'
        printf "Launching GELF UDP..."
        curl --output /dev/null --silent \\
          -u "admin:$GRAYLOG_PASSWORD_SECRET" \\
          -H "Content-Type: application/json" -H "x-requested-by: localhost" \\
          -d "$json" http://graylog-web:9000/api/system/inputs \\
          --connect-timeout 10 \\
          --retry 20 \\
          --max-time 20 \\
          --retry-max-time 120 \\
          --retry-connrefused

        if [[ $? -ne 0 ]]; then
          echo " Creation failed."
        else
          echo
        fi

        json='{
          "title":"Filebeats",
          "type":"org.graylog.plugins.beats.Beats2Input",
          "configuration":{
            "bind_address":"0.0.0.0",
            "port":5044,
            "no_beats_prefix":false
          },
          "global":true
        }'
        printf "Launching Beats2Input..."
        curl --output /dev/null --silent \\
          -u "admin:$GRAYLOG_PASSWORD_SECRET" \\
          -H "Content-Type: application/json" -H "x-requested-by: localhost" \\
          -d "$json" http://graylog-web:9000/api/system/inputs \\
          --connect-timeout 10 \\
          --retry 20 \\
          --max-time 20 \\
          --retry-max-time 120 \\
          --retry-connrefused

        if [[ $? -ne 0 ]]; then
          echo " Creation failed."
        else
          echo
        fi

## Specify Elasticsearch version from requirement dependencies. Ignore this seection if you install Elasticsearch manually.
## Note: Graylog 2.4 requires Elasticsearch version <= 5.6
elasticsearch:
  image:
    repository: "docker.elastic.co/elasticsearch/elasticsearch-oss"
    tag: "6.8.13"
  client:
    replicas: 2
  master:
    replicas: 3
  data:
    replicas: 2
  cluster:
    env:
      MINIMUM_MASTER_NODES: 1
    xpackEnable: false

mongodb:
  architecture: "replicaset"
  useStatefulSet: true
  replicaCount: 3
  auth:
    enabled: false


```

Please let me know if additional information is needed ?
Original plan is to migrate from Stable chart version 1.6.10
Not sure what i am doing wrong here .

**Comment by akramwaseem** [comment]
@KongZ -- anyidea why this is happening.
I tried dofferent chart versions with different versions of graylog. issue is still the same.

**Comment by KongZ** [comment]
it is not a Graylog problem. Checkout your mongodb deployment. 
Is `graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local` exists

**Comment by akramwaseem** [comment]
@KongZ  -- so, when i run the helm chart, i can see few pods with are being brought up

`
graylog-0                                       0/1     Terminating        1          6m46s   
graylog-elasticsearch-client-5fb4bf5d7d-4rf8x   0/1     Terminating        0          6m46s   
graylog-elasticsearch-client-5fb4bf5d7d-ctn65   0/1     Terminating        0          6m46s   1
graylog-elasticsearch-data-1                    0/1     Terminating        0          5m39s   
graylog-elasticsearch-master-1                  0/1     Terminating        0          5m50s   
graylog-mongodb-arbiter-0                       1/1     Terminating        2          6m46s   
graylog-provisioner-job-v4qgp

`

only part i dont understand is this 

`
2021-07-13T21:29:10.574859743Z cannot resolve host "graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local": lookup graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local: no such host
2021-07-13T21:29:15.653681250Z cannot resolve host "graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local": lookup graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local: no such host
2021-07-13T21:29:20.741970336Z cannot resolve host "graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local": lookup graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local: no such host
2021-07-13T21:29:25.820613914Z cannot resolve host "graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local": lookup graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local: no such host
2021-07-13T21:29:30.835459367Z cannot resolve host "graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local": lookup graylog-mongodb-0.graylog-mongodb-headless.svfb.svc.cluster.local: no such host
`

where is it tryig to get that from ?
is it doing from the values i passed 

`
  --set graylog.mongodb.uri=mongodb://mongodb-mongodb-replicaset-0.mongodb-mongodb-replicaset.graylog.svfb.svc.cluster.local:27017/graylog?replicaSet=rs0 \
  --set graylog.elasticsearch.hosts=http://elasticsearch-client.graylog.svfb.svc.cluster.local:9200 \
`

I am kind of lost here on what I am doing wrong ?
do you think there should be one more pod with mongodb should have deployed as part of the chart or does 'graylog-mongodb-arbiter-0 ' is not the right pod
when I exec into the pod I can see it has a hostname with `   graylog-mongodb-arbiter-0.graylog-mongodb-arbiter-headless.svfb.svc.cluster.local `
