### ISSUE TITLE
Graylog - IndexFieldTypePollerPeriodical Errors after graylog restart

### ISSUE THREAD

**Issue by kondas** [KongZ/charts#52]
**Describe the bug**
Installed latest version of Graylog chart, without built in Elasticsearch subchart. The Elasticsearch cluster is installed using official chart, version 7.13.2.  After Graylog statefulset instance is restarted, logs are flooded with E11000 errors
Helm Version:v3.5.4
Kubernetes Version: 1.21.2
Chart version: 9.3.1

```
2021-07-12 18:26:46,126 ERROR   [IndexFieldTypePollerPeriodical] - Couldn't update field types for index set <Default index set/60ec872f122d06319a7f9c2d> - {}
com.mongodb.DuplicateKeyException: Write failed with error code 11000 and error message 'E11000 duplicate key error collection: graylog.index_field_types index: index_name_1 dup key: { index_name: "graylog_0" }'
	at com.mongodb.operation.BaseWriteOperation.convertBulkWriteException(BaseWriteOperation.java:191) ~[graylog.jar:?]
	at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:155) ~[graylog.jar:?]
	at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:52) ~[graylog.jar:?]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:213) ~[graylog.jar:?]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:182) ~[graylog.jar:?]
	at com.mongodb.DBCollection.executeWriteOperation(DBCollection.java:356) ~[graylog.jar:?]
	at com.mongodb.DBCollection.update(DBCollection.java:588) ~[graylog.jar:?]
	at com.mongodb.DBCollection.update(DBCollection.java:507) ~[graylog.jar:?]
	at com.mongodb.DBCollection.update(DBCollection.java:482) ~[graylog.jar:?]
	at com.mongodb.DBCollection.update(DBCollection.java:459) ~[graylog.jar:?]
	at org.mongojack.JacksonDBCollection.update(JacksonDBCollection.java:516) ~[graylog.jar:?]
	at org.mongojack.JacksonDBCollection.update(JacksonDBCollection.java:592) ~[graylog.jar:?]
	at org.graylog2.indexer.fieldtypes.IndexFieldTypesService.lambda$upsert$0(IndexFieldTypesService.java:82) ~[graylog.jar:?]
	at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78) ~[graylog.jar:?]
	at com.github.rholder.retry.Retryer.call(Retryer.java:160) ~[graylog.jar:?]
	at org.graylog2.database.MongoDBUpsertRetryer.run(MongoDBUpsertRetryer.java:56) ~[graylog.jar:?]
	at org.graylog2.indexer.fieldtypes.IndexFieldTypesService.upsert(IndexFieldTypesService.java:82) ~[graylog.jar:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_282]
	at org.graylog2.indexer.fieldtypes.IndexFieldTypePollerPeriodical.lambda$schedule$4(IndexFieldTypePollerPeriodical.java:220) ~[graylog.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_282]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_282]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_282]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

**Comment by KongZ** [comment]
Hi, this is the Graylog or Elasticsearch issue. If the problem is persists and you need help, you can raise an issue directly to Graylog product. The error here is not related to helm chart :)
