### ISSUE TITLE
Parent directory /usr/share/graylog/data/journal for Node ID file at /usr/share/graylog/data/journal/node-id is not writable

### ISSUE THREAD

**Issue by Timboul** [KongZ/charts#72]
Hello everyone and thanks for your work. 
I have a little issue when installing this chart.

I have already deployed mongo and elastic on my cluster.
The cluster is composed of 3 nodes (1 master, 2 workers) running with ubuntu 20.04.1  and all nodes use the same NFS server to create PVC with the help of the nfs-subdir-external-provisioner as storage class.

If i set the persistence to false, everything works well, but when i set it to true i have the following error.

`
/entrypoint.sh: line 10: /k8s/kubectl: No such file or directory
/entrypoint.sh: line 11: /k8s/kubectl: No such file or directory
Current master is 
Self IP is 
Launching graylog-0 as master
/entrypoint.sh: line 17: /k8s/kubectl: No such file or directory
Starting graylog
Graylog Home /usr/share/graylog
Graylog Plugin Dir /usr/share/graylog/plugin
Graylog Elasticsearch Version 7
2021-09-17 14:40:36,942 ERROR   [CmdLineTool] - Invalid configuration - {}
com.github.joschi.jadconfig.ValidationException: Parent directory /usr/share/graylog/data/journal for Node ID file at /usr/share/graylog/data/journal/node-id is not writable
	at org.graylog2.Configuration$NodeIdFileValidator.validate(Configuration.java:377) ~[graylog.jar:?]
	at org.graylog2.Configuration$NodeIdFileValidator.validate(Configuration.java:359) ~[graylog.jar:?]
	at com.github.joschi.jadconfig.JadConfig.validateParameter(JadConfig.java:215) ~[graylog.jar:?]
	at com.github.joschi.jadconfig.JadConfig.processClassFields(JadConfig.java:148) ~[graylog.jar:?]
	at com.github.joschi.jadconfig.JadConfig.process(JadConfig.java:99) ~[graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.processConfiguration(CmdLineTool.java:420) [graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:236) [graylog.jar:?]
	at org.graylog2.bootstrap.Main.main(Main.java:45) [graylog.jar:?]
`

I tried to chown to 1100 the folder of the PVC created "journal-graylog-0" but it does not help.
I also tried to use privileged option but without success ...
Do you have an idea of what i am doing wrong here ?

Thanks

**Comment by KongZ** [comment]
What is your PVC access mode? It should be `ReadWriteOnce` or `ReadWriteMany`
And make sure that `nfs-subdir-external-provisioner` has permission to write into the folder.

**Comment by hollowdew** [comment]
Hello, I know that was an old issue but I just started using this graylog helm chart, and I am facing the exact same issue.
I am using k3s with nfs-subdir-external-provisioner and configured the values.yaml to not run in privileged mode.
I use the nfs-subdir-external-provisioner as my default storage class and had no problem with permissions by now.
Any help is much appreciated, thanks for all the effort in this project.

**Comment by hollowdew** [comment]
I just discovered that if I manually create the file **node-id** in the journal folder, the issue is fixed.
